server:
  port: 9527

#spring:
#  application:
#    name: cloud-gateway
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: get_user
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          predicates:
          # 断言，路径相匹配的进行路由    通过本项目（9527）只能进和断言相匹配的 eg: - Path=/get/user/**
            - Path=/get/user/**

        - id: get_user2
#          lb://  后面跟名称，xxx项目中的spring.application.name=provider-01
          uri: lb://provider-01
          predicates:
            - Path=/get/user/haha/**         # 断言，路径相匹配的进行路由
#        - id: get_user2
#            uri: http://localhost:8001
#            predicates:
#              - Path=/get/user/haha/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka